export enum ENotificationTemplateType {
  WELCOME = 'WELCOME',
  POST_LIKED = 'POST_LIKED',

  POST_COMMENTED = 'POST_COMMENTED',
  POST_REACTED = 'POST_REACTED',
  COMMENT_REPLIED = 'COMMENT_REPLIED',
  USER_FOLLOWED = 'USER_FOLLOWED',
}
